name: Release Deployment

on:
  push:
    branches:
      - main

permissions: write-all
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.4.0'

      - name: Install Dependencies
        run: |
          npm --version
          node --version
          npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release

